package main

var foods = []string{
	"Bahn Mi",
	"Baked Beans",
	"Banana Pudding",
	"Beef Bourguignon With White Rice",
	"Bibimbap",
	"Biscuits and Sausage Gravy",
	"Biryani",
	"Bulgogi",
	"Burger",
	"Burrito",
	"Buttered Scallops With Hoisin Sauce",
	"Calzone",
	"Caprese Salad",
	"Catfish Fry",
	"Ceviche",
	"Chicken Sandwich",
	"Chicken Satay with Brown Rice",
	"Chicken Tendies",
	"Chicken Wings",
	"Chili-Lime Salmon With Basmati Rice",
	"Chow Fun",
	"Cuban Sandwich",
	"Cumin Ground Lamb and Steamed Broccoli",
	"Doner Kebab",
	"Fajitas",
	"Falafel",
	"Fish and Chips",
	"Fish Tacos",
	"Fried Chicken",
	"Fried Rice",
	"Fries",
	"Grilled Cheese",
	"Gumbo",
	"Gyro",
	"Gyoza",
	"Hash Browns",
	"Hotpot",
	"Hush Puppies",
	"Kathi Rolls",
	"Japanese Curry",
	"Jerk Chicken with Carbbiean Fried Rice",
	"Kimchi Fried Rice",
	"Lasagne alla Bolognese",
	"Mac & Cheese",
	"Masala Dosa With Basmati Rice",
	"Massaman Curry",
	"Mediterranean Pita With Falafel and Hummus",
	"Mexican Sandwich",
	"Orange Chicken",
	"Pad Thai",
	"Paella",
	"Parfait",
	"Pho",
	"Pierogis",
	"Pizza",
	"Po' boy",
	"Poke Bowl With Quinoa",
	"Quesadilla",
	"Ramen",
	"Ribeye",
	"Ribs",
	"Rissoto"
	"Sandwich",
	"Scrambled Eggs",
	"Shandong Style, Pan-Fried Dumplings With Scallion Pancakges",
	"Shrimp and Grits",
	"Soup",
	"Steak",
	"Spaghetti",
	"Spring Rolls",
	"Stromboli",
	"Sushi",
	"Tacos",
	"Tamales",
	"Tandoori Chicken",
	"Tempura",
	"Teriyaki Chicken",
	"Tilapia With Jasmine Rice and Asparagus",
	"Tonkatsu",
	"Veal Milanese With Fresh Corn Polenta",
	"Venezuelan Arepas",
	"Wrap",
	"Wings",
	"Wonton Soup",
	"Yakitori",
}

var restaurants = []string{
	"Alehouse",
	"BurgerFi",
	"Carls Jr",
	"Checkers",
	"Chick-fil-a",
	"Chili's",
	"Chipotle",
	"Crackerbarrel",
	"Cuban Guys",
	"Dennys",
	"Dominos",
	"Firehouse Subs",
	"Hardy's",
	"in-n-out",
	"Jimmy Johns",
	"KFC",
	"La Carreta",
	"Los Verdes",
	"MOD Pizza",
	"Moe's",
	"Olive Garden",
	"Panda Express",
	"Panera Bread",
	"Papa Johns",
	"PDQ",
	"Pei Wei",
	"PF Changs",
	"Pizza Hut",
	"Pollo Tropical",
	"Popeye's",
	"Sergio's",
	"Sonic",
	"Steak and Shake",
	"Subway",
	"Taco Bell",
	"TGI Fridays",
	"Wendys",
	"What-a-burger",
	"Zaxby's",
}
